name: Daily Commit

on:
  schedule:
    - cron: "30 5 * * *"  # Runs daily at 5:30 AM UTC (Adjust as needed)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: 21f1001892@ds.study.iitm.ac.in
        run: |
          echo "21f1001892@ds.study.iitm.ac.in"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make a Dummy Change
        run: |
          echo "$(date)" >> daily-log.txt

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "21f1001892@ds.study.iitm.ac.in"

      - name: Commit and Push Changes
        run: |
          git add daily-log.txt
          git commit -m "Automated commit: $(date)"
          git push
